steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/ayush-server-gcp/ms-engage-server:latest', 'server/.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/ayush-server-gcp/ms-engage-server:latest']